category_:
    pattern:  /
    defaults: { _controller: "AcmeBudgetTrackerBundle:Category:index" }

category__show:
    pattern:  /{id}/show
    defaults: { _controller: "AcmeBudgetTrackerBundle:Category:show" }

category__new:
    pattern:  /new
    defaults: { _controller: "AcmeBudgetTrackerBundle:Category:new" }

category__create:
    pattern:  /create
    defaults: { _controller: "AcmeBudgetTrackerBundle:Category:create" }
    requirements: { _method: post }

category__edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AcmeBudgetTrackerBundle:Category:edit" }

category__update:
    pattern:  /{id}/update
    defaults: { _controller: "AcmeBudgetTrackerBundle:Category:update" }
    requirements: { _method: post }

category__delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AcmeBudgetTrackerBundle:Category:delete" }
    requirements: { _method: post }