<?php

namespace Acme\BudgetTrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DebtsLoansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebtLoanRepository extends EntityRepository
{
    public function findByReturnedUserAndCategory($user, $category, $returned = 0)
    {
        $q = $this
            ->createQueryBuilder('dl')
            ->where('dl.user = :user')
            ->andWhere('dl.category = :category')
                ->andWhere('dl.returned = :returned')
            ->setParameter('user', $user)
            ->setParameter('category', $category)
            ->setParameter('returned', $returned)
             ->getQuery();
        
        return $q->getResult();
    } 
}
