<?php

namespace Acme\BudgetTrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseRepository extends EntityRepository
{
    public function findExpensesForDate($user, $date)
    {
        $q = $this
            ->createQueryBuilder('e')
            ->where('e.date = :date')
            ->andWhere('e.user = :user')
            ->setParameter('date', $date)
            ->setParameter('user', $user)
             ->getQuery();
        
        return $q->getResult();
    }
}