<?php

namespace Acme\BudgetTrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseRepository extends EntityRepository
{
    
    public function findExpensesForDate($fromDate, $toDate, $user, $category)
    {
        $q = $this
            ->createQueryBuilder('e')
            ->where('e.date >= :fromDate')
            ->andWhere('e.date < :toDate')
            ->andWhere('e.user = :user')
            ->andWhere('e.category <> :category')
            ->setParameter('fromDate', $fromDate)
            ->setParameter('toDate', $toDate)
            ->setParameter('user', $user)
            ->setParameter('category', $category)
             ->getQuery();
        
        return $q->getResult();
    }
    
    //used
    public function findExpensesByMonth($month, $year, $user, $category, $returned = 0)
    {
        $emConfig = $this->getEntityManager()->getConfiguration();
        $emConfig->addCustomDatetimeFunction('YEAR', 'DoctrineExtensions\Query\Mysql\Year');
        $emConfig->addCustomDatetimeFunction('MONTH', 'DoctrineExtensions\Query\Mysql\Month');
        
        $q = $this
            ->createQueryBuilder('e')
            ->where('MONTH(e.date) = :month') 
            ->andWhere('YEAR(e.date) = :year')
            ->andWhere('e.user = :user')
            ->andWhere('e.category <> :category')
            ->andWhere('e.returned = :returned')
            ->orderBy('e.category', 'ASC')
            ->setParameter('month', $month)
            ->setParameter('year', $year)
            ->setParameter('user', $user) 
            ->setParameter('category', $category)
            ->setParameter('returned', $returned)           
            ->getQuery();
        
        return $q->getResult();
    } 
    
    //used
    public function getSumByMonth($month, $year, $user, $returned = 0)
    {
        $emConfig = $this->getEntityManager()->getConfiguration();
        $emConfig->addCustomDatetimeFunction('YEAR', 'DoctrineExtensions\Query\Mysql\Year');
        $emConfig->addCustomDatetimeFunction('MONTH', 'DoctrineExtensions\Query\Mysql\Month');
        
        $q = $this->createQueryBuilder('e')
            ->add('select', 'SUM(e.price)')
            ->where('MONTH(e.date) = :month')
            ->andWhere('YEAR(e.date) = :year')
            ->andWhere('e.user = :user') 
            ->andWhere('e.returned = :returned') 
            ->setParameter('month', $month)
            ->setParameter('year', $year)
            ->setParameter('user', $user)
            ->setParameter('returned', $returned)
            ->getQuery();

        return $q->getSingleScalarResult();
    }
    
    //used
    public function findSumBetweenDates($start_date, $end_date, $user)
    {
        $q = $this
            ->createQueryBuilder('e')
            ->add('select', 'SUM(e.price)')
            ->where('e.date >= :start_date')
            ->andWhere('e.date < :end_date')
            ->andWhere('e.user = :user')
            ->setParameter('start_date', $start_date)
            ->setParameter('end_date', $end_date)
            ->setParameter('user', $user)
             ->getQuery();
        
        return $q->getSingleScalarResult();
    }
  
    public function findByCategoriesAndDates($start_date, $end_date, $q, $user, $category)
    {
         $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT e FROM AcmeBudgetTrackerBundle:Expense e WHERE e.user = ?1 AND e.date >= ?2 AND e.date < ?3 AND e.category <> ?4'.$q. 'ORDER BY e.category, e.date');
        $query->setParameter(1, $user);
        $query->setParameter(2, $start_date);
        $query->setParameter(3, $end_date);
        $query->setParameter(4, $category);
        
        return $query->getResult();
    }

    public function countNotReturned($user, $returned)
    {
        $q = $this
            ->createQueryBuilder('c')
            ->select('COUNT(c.id)') 
            ->where('c.user = :user')
            ->andWhere('c.category = :debts')
            ->andWhere('c.returned = :returned')
            ->setParameter('user', $user)
            ->setParameter('debts', 'Debts')
            ->setParameter('returned', $returned)
             ->getQuery();
       
        return $q->getSingleScalarResult();
    }


    public function findByCategory($user, $category, $returned = 0)
    {
        $q = $this
            ->createQueryBuilder('e') 
            ->where('e.user = :user')
            ->andWhere('e.category = :category')
            ->andWhere('e.returned = :returned')
            ->setParameter('user', $user)
            ->setParameter('category', $category)
            ->setParameter('returned', $returned)
             ->getQuery();
       
        return $q->getResult();
    }
}

