<?php

namespace Acme\BudgetTrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MonthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthRepository extends EntityRepository
{
    public function countByNameAndUser($name, $user)
    {
        $q = $this
            ->createQueryBuilder('m')
            ->select('COUNT(m.id)') 
            ->where('m.name = :name')
            ->andWhere('m.user = :user')
            ->setParameter('name', $name)
            ->setParameter('user', $user)
             ->getQuery();
        
        return $q->getSingleScalarResult();
    }
    
        public function findByUserLimit($user)
    {
        $q = $this
            ->createQueryBuilder('m')
            ->where('m.user = :user')
            ->orderBy('m.date', 'DESC')
            ->setMaxResults(12)
            ->setFirstResult(0)
            ->setParameter('user', $user)
             ->getQuery();
       
        return $q->getResult();
    }
    
            public function findByUser($user)
    {
        $q = $this
            ->createQueryBuilder('m')
            ->where('m.user = :user')
            ->orderBy('m.date', 'ASC')
            ->setParameter('user', $user)
             ->getQuery();
       
        return $q->getResult();
    }
    
    //used
    public function findMonth($month, $year, $user)
    {
        $q = $this
            ->createQueryBuilder('m')
            ->where('MONTH(m.date) = :month')
            ->andWhere('YEAR(m.date) = :year')
            ->andWhere('m.user = :user')      
            ->setParameter('month', $month)
            ->setParameter('year', $year)
            ->setParameter('user', $user)     
             ->getQuery();
       
        return $q->getResult(); 
    }
}
