#From FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
#BudgetTracker
home:
    pattern:  /
    defaults: { _controller: AcmeBudgetTrackerBundle:Home:index }
    
expenses:
    pattern: /expenses
    defaults: { _controller: AcmeBudgetTrackerBundle:Expenses:expenses }
    
reports:
    pattern: /reports
    defaults: { _controller: AcmeBudgetTrackerBundle:Reports:reports }
    
categories:
    pattern: /categories
    defaults: { _controller: AcmeBudgetTrackerBundle:Categories:categories }
    
months:
    pattern: /months
    defaults: { _controller: AcmeBudgetTrackerBundle:Months:months } 