#From FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
#BudgetTracker
home:
    pattern:  /
    defaults: { _controller: AcmeBudgetTrackerBundle:Home:index }
    
goodbye:
    pattern: /goodbye
    defaults: { _controller: AcmeBudgetTrackerBundle:Goodbye:goodbye }
    
expenses:
    pattern: /expenses
    defaults: { _controller: AcmeBudgetTrackerBundle:Expenses:expenses }
    
reports:
    pattern: /reports
    defaults: { _controller: AcmeBudgetTrackerBundle:Reports:reports }
    
categories:
    pattern: /categories/{_locale}
    defaults: { _controller: AcmeBudgetTrackerBundle:Categories:categories, _locale: bg }
    requirements:
        _locale: en|bg
        
categories:
    pattern: /categories/{_locale}
    defaults: { _controller: AcmeBudgetTrackerBundle:Categories:categories, _locale: en }
    requirements:
        _locale: en|bg
    
months:
    pattern: /months
    defaults: { _controller: AcmeBudgetTrackerBundle:Months:months } 
    
create_category:
    pattern: /create_category
    defaults: { _controller: AcmeBudgetTrackerBundle:Categories:createCategory }
    
edit_category:
    pattern: /edit_category/{id}
    defaults: { _controller: AcmeBudgetTrackerBundle:Categories:editCategory }
    
delete_category:
    pattern: /delete_category/{id}
    defaults: { _controller: AcmeBudgetTrackerBundle:Categories:deleteCategory }
    
create_expense:
    pattern: /create_expense
    defaults: { _controller: AcmeBudgetTrackerBundle:Expenses:createExpense }