parameters:
#    acme_budget_tracker.example.class: Acme\BudgetTrackerBundle\Example

services:
    acme_user.profile.form.type:
        class: Acme\BudgetTrackerBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: acme_user_profile }
#    acme_budget_tracker.example:
#        class: %acme_budget_tracker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
