parameters:
#    acme_budget_tracker.example.class: Acme\BudgetTrackerBundle\Example

services:
#    acme_budget_tracker.example:
#        class: %acme_budget_tracker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
